version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  heroku/deploy-via-git:
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            git push heroku main
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
