version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  heroku/deploy-via-git:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - heroku/install
      - heroku/deploy-via-git
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
