version: 2.1

jobs:
  build:
    docker:
      - image: node:16.0.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: deploy
          command: render deploy
