version: 2.1
orbs:
  heroku: circleci/heroku@2.0
jobs:
  testing:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Linting
          command: |
            npm run lint
            mkdir /eslint-result
      - store_artifacts:
          path: /eslint-result
          destination: eslint-result.xml
      - run:
          name: Check Code quality
          command: |
            if [ -s eslint-result.xml ]; then
              echo "Linting errors found, failing the build."
              exit 1
            else
              echo "Linting passed, continuing the build."
              # rest of the commands to build and test the project
            fi
      - run:
          name: Test the app
          command: npm test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Set the stack of your app to container
          command: |
            heroku stack:set container --app $HEROKU_APP_NAME
      - heroku/deploy-via-git
      - run:
          name: Check deployment status
          command: |
            heroku ps --app $HEROKU_APP_NAME
workflows:
  heroku_deploy:
    jobs:
      - testing
      - deploy:
          requires:
            - testing
