version: 2

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  run_and_test:
    docker:
      # replace with your preferred image
      - image: circleci/node:latest
    steps:
      - checkout
      # Install dependencies and run tests
      - run:
          name: Install and test
          command: |
            npm install
            npm test

      - run:
          name: Test Cases
          command: |
            npm test

  heroku/deploy-via-git:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          environment:
            api-key: 59f76567-d0d5-4033-9175-ef20b931f3bf
            app-name: full-stack-backend
            branch: master
            force: false
workflows:
  version: 2
  example-workflow:
    jobs:
      - run_and_test
      - heroku/deploy-via-git
