version: 2.1
jobs:
  build:
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  deploy:
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:59f76567-d0d5-4033-9175-ef20b931f3bf@git.heroku.com/full-stack-backend.git master
