version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: node:16.0.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run: npm install -g render-cli
    deploy:
      working_directory: ~/app
      steps:
        - run:
            name: Deploy to Heroku
            command: |
              git remote add heroku https://heroku:59f76567-d0d5-4033-9175-ef20b931f3bf@git.heroku.com/full-stack-backend.git
              git push heroku master
    workflows:
      version: 2
      build_and_deploy:
        jobs:
          - build
          - deploy:
              requires:
                - build
