version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:14.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:59f76567-d0d5-4033-9175-ef20b931f3bf@git.heroku.com/full-stack-backend.git master
