version: 2.1

orbs:
  heroku-deploy: circleci/heroku-deploy@3.2.2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # Install dependencies and run tests
      - run:
          name: Install and test
          command: |
            npm install
            npm test

      - run:
          name: Test Cases
          command: |
            npm test
        environment:
          NODE_ENV: test

      # Deploy to Heroku
      - heroku-deploy/setup-auth:
          api-key: 59f76567-d0d5-4033-9175-ef20b931f3bf
      - heroku-deploy/deploy:
          app-name: full-stack-backend
          command: |
            npm install
            npm run build
            npm start

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
