version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  heroku/deploy-via-git:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
            heroku run npm run build
workflows:
  version: 2
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
