version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      # Install dependencies and run tests
      - run:
          name: Install and test
          command: |
            npm install
            npm test

      # Deploy to Heroku
      - run:
          name: Deploy to Heroku
          command: |
            git branch master
            git push https://heroku:59f76567-d0d5-4033-9175-ef20b931f3bf@git.heroku.com/full-stack-backend.git master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
