version: 2.1

jobs:
  build:
    docker:
      - image: node:16.0.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run: npm install -g render-cli
      - run:
          name: Deploy to Render
          command: |
            curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer rnd_ZNidmPHjo6gJtazNOtGec4q8PBTz" -d '{"image":"username/fullstack-backend:2"}' https://api.render.com/deploy
