version: 2.1
jobs:
  build:
    docker:
      - image: node:16
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
  deploy:
    steps:
      - run:
          name: Deploy to Heroku
          command: |
            git remote add heroku https://heroku:59f76567-d0d5-4033-9175-ef20b931f3bf@git.heroku.com/full-stack-backend.git
            git push heroku master
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
